"""clean control plane baseline"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_rules",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("event_types", sa.JSON(), nullable=False),
        sa.Column("source_filters", sa.JSON(), nullable=False),
        sa.Column("pipeline_filters", sa.JSON(), nullable=False),
        sa.Column("connector_filters", sa.JSON(), nullable=False),
        sa.Column("cooldown_seconds", sa.Integer(), nullable=False),
        sa.Column("notification_policy", sa.String(length=40), nullable=False),
        sa.Column("send_recovery", sa.Boolean(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_created", "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("claimed_by", sa.String(length=120), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_jobs_claim", "jobs", ["status", "next_attempt_at", "lease_expires_at"], unique=False
    )
    op.create_index(op.f("ix_jobs_claimed_by"), "jobs", ["claimed_by"], unique=False)
    op.create_index(op.f("ix_jobs_lease_expires_at"), "jobs", ["lease_expires_at"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "secret_references",
        sa.Column("ciphertext", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "connections",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("capabilities_json", sa.JSON(), nullable=False),
        sa.Column("secret_ref", sa.Uuid(), nullable=True),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_test_status", sa.String(length=20), nullable=True),
        sa.Column("last_test_message", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "category IN ('DATABASE','OBJECT_STORAGE')", name="ck_connections_category"
        ),
        sa.CheckConstraint(
            "provider IN ('POSTGRESQL','MYSQL','AWS_S3','MINIO')", name="ck_connections_provider"
        ),
        sa.ForeignKeyConstraint(["secret_ref"], ["secret_references.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_connections_category"), "connections", ["category"], unique=False)
    op.create_index(op.f("ix_connections_provider"), "connections", ["provider"], unique=False)
    op.create_index(op.f("ix_connections_status"), "connections", ["status"], unique=False)
    op.create_table(
        "kafka_clusters",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("bootstrap_servers", sa.String(), nullable=False),
        sa.Column("security_protocol", sa.String(), nullable=False),
        sa.Column("secret_ref", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["secret_ref"],
            ["secret_references.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "notification_channels",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("config_encrypted", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["config_encrypted"], ["secret_references.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_notification_channels_enabled"), "notification_channels", ["enabled"], unique=False
    )
    op.create_index(
        op.f("ix_notification_channels_type"), "notification_channels", ["type"], unique=False
    )
    op.create_table(
        "alert_rule_channels",
        sa.Column("alert_rule_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["alert_rule_id"], ["alert_rules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["channel_id"], ["notification_channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alert_rule_id", "channel_id"),
    )
    op.create_table(
        "connect_clusters",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("kafka_cluster_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["kafka_cluster_id"],
            ["kafka_clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_connect_clusters_kafka_cluster_id"),
        "connect_clusters",
        ["kafka_cluster_id"],
        unique=False,
    )
    op.create_table(
        "kafka_topics",
        sa.Column("kafka_cluster_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["kafka_cluster_id"],
            ["kafka_clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kafka_cluster_id", "name"),
    )
    op.create_table(
        "schema_versions",
        sa.Column("source_connection_id", sa.Uuid(), nullable=False),
        sa.Column("schema_name", sa.String(), nullable=False),
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_json", sa.JSON(), nullable=False),
        sa.Column("schema_hash", sa.String(length=64), nullable=False),
        sa.Column("diff_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_connection_id"], ["connections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_connection_id", "schema_name", "table_name", "version"),
    )
    op.create_index(
        "ix_schema_lookup",
        "schema_versions",
        ["source_connection_id", "schema_name", "table_name"],
        unique=False,
    )
    op.create_table(
        "source_tables",
        sa.Column("source_connection_id", sa.Uuid(), nullable=False),
        sa.Column("schema_name", sa.String(length=128), nullable=False),
        sa.Column("table_name", sa.String(length=128), nullable=False),
        sa.Column("primary_key_columns", sa.JSON(), nullable=False),
        sa.Column("columns_json", sa.JSON(), nullable=False),
        sa.Column("indexes_json", sa.JSON(), nullable=False),
        sa.Column("estimated_rows", sa.BigInteger(), nullable=True),
        sa.Column("estimated_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("cdc_ready", sa.Boolean(), nullable=False),
        sa.Column("cdc_status", sa.String(), nullable=False),
        sa.Column("cdc_issues", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_connection_id"], ["connections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_connection_id", "schema_name", "table_name"),
    )
    op.create_table(
        "connectors",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("connector_type", sa.String(), nullable=False),
        sa.Column("connect_cluster_id", sa.Uuid(), nullable=False),
        sa.Column("connector_class", sa.String(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("desired_state", sa.String(), nullable=False),
        sa.Column("actual_state", sa.String(), nullable=False),
        sa.Column("runtime_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connect_cluster_id"],
            ["connect_clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connect_cluster_id", "name"),
    )
    op.create_table(
        "pipelines",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("source_connection_id", sa.Uuid(), nullable=False),
        sa.Column("kafka_cluster_id", sa.Uuid(), nullable=False),
        sa.Column("connect_cluster_id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=True),
        sa.Column("topic_prefix", sa.String(length=120), nullable=False),
        sa.Column("snapshot_mode", sa.String(), nullable=False),
        sa.Column("config_options", sa.JSON(), nullable=False),
        sa.Column("desired_state", sa.String(), nullable=False),
        sa.Column("actual_state", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connect_cluster_id"],
            ["connect_clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kafka_cluster_id"],
            ["kafka_clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_connection_id"],
            ["connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("topic_prefix"),
    )
    op.create_index(op.f("ix_pipelines_actual_state"), "pipelines", ["actual_state"], unique=False)
    op.create_index(
        op.f("ix_pipelines_source_connection_id"),
        "pipelines",
        ["source_connection_id"],
        unique=False,
    )
    op.create_table(
        "alerts",
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.String(length=120), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("pipeline_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_name", sa.String(length=120), nullable=True),
        sa.Column("component", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.String(length=2000), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=255), nullable=True),
        sa.Column("silenced_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("silenced_by", sa.String(length=255), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_alerts_created_at", "alerts", ["created_at"], unique=False)
    op.create_index(op.f("ix_alerts_event_type"), "alerts", ["event_type"], unique=False)
    op.create_index(op.f("ix_alerts_fingerprint"), "alerts", ["fingerprint"], unique=False)
    op.create_index(
        "ix_alerts_fingerprint_status", "alerts", ["fingerprint", "status"], unique=False
    )
    op.create_index(op.f("ix_alerts_pipeline_id"), "alerts", ["pipeline_id"], unique=False)
    op.create_index(
        "ix_alerts_pipeline_severity", "alerts", ["pipeline_id", "severity"], unique=False
    )
    op.create_index(op.f("ix_alerts_severity"), "alerts", ["severity"], unique=False)
    op.create_index(op.f("ix_alerts_source_id"), "alerts", ["source_id"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_index(
        "uq_alerts_active_fingerprint",
        "alerts",
        ["fingerprint"],
        unique=True,
        postgresql_where=sa.text("status IN ('firing', 'acknowledged', 'silenced')"),
        sqlite_where=sa.text("status IN ('firing', 'acknowledged', 'silenced')"),
    )
    op.create_table(
        "pipeline_destinations",
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("destination_connection_id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("delivery_type", sa.String(length=30), nullable=False),
        sa.Column("delivery_mode", sa.String(), nullable=False),
        sa.Column("topic_mapping_json", sa.JSON(), nullable=False),
        sa.Column("configuration_json", sa.JSON(), nullable=False),
        sa.Column("desired_state", sa.String(), nullable=False),
        sa.Column("actual_state", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_connection_id"],
            ["connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connector_id"),
        sa.UniqueConstraint("destination_connection_id", "name"),
    )
    op.create_index(
        op.f("ix_pipeline_destinations_actual_state"),
        "pipeline_destinations",
        ["actual_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_destinations_destination_connection_id"),
        "pipeline_destinations",
        ["destination_connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_destinations_pipeline_id"),
        "pipeline_destinations",
        ["pipeline_id"],
        unique=False,
    )
    op.create_table(
        "pipeline_metrics",
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("values_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline_tables",
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("schema_name", sa.String(), nullable=False),
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("topic_name", sa.String(), nullable=False),
        sa.Column("primary_key_columns", sa.JSON(), nullable=False),
        sa.Column("destination_schema", sa.String(length=128), nullable=True),
        sa.Column("destination_table", sa.String(length=128), nullable=True),
        sa.Column("initial_data_strategy", sa.String(), nullable=False),
        sa.Column("delete_strategy", sa.String(), nullable=False),
        sa.Column("snapshot_status", sa.String(), nullable=False),
        sa.Column("cdc_status", sa.String(), nullable=False),
        sa.Column("schema_status", sa.String(), nullable=False),
        sa.Column("destination_status", sa.String(), nullable=False),
        sa.Column("snapshot_rows_processed", sa.BigInteger(), nullable=True),
        sa.Column("snapshot_estimated_rows", sa.BigInteger(), nullable=True),
        sa.Column("snapshot_current_chunk", sa.String(length=255), nullable=True),
        sa.Column("snapshot_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snapshot_last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snapshot_finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pipeline_id", "schema_name", "table_name"),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("claimed_by", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["channel_id"], ["notification_channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alert_id", "channel_id", "kind"),
    )
    op.create_index(
        op.f("ix_notification_deliveries_alert_id"),
        "notification_deliveries",
        ["alert_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_channel_id"),
        "notification_deliveries",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_status"),
        "notification_deliveries",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_notification_delivery_queue",
        "notification_deliveries",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_table(
        "pipeline_events",
        sa.Column("pipeline_id", sa.Uuid(), nullable=True),
        sa.Column("destination_connection_id", sa.Uuid(), nullable=True),
        sa.Column("delivery_id", sa.Uuid(), nullable=True),
        sa.Column("connector_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("component", sa.String(length=80), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("technical_details", sa.JSON(), nullable=False),
        sa.Column("recoverable", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("connector_name", sa.String(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["delivery_id"], ["pipeline_destinations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["destination_connection_id"], ["connections.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_events_connector_id"), "pipeline_events", ["connector_id"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_events_delivery_id"), "pipeline_events", ["delivery_id"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_events_destination_connection_id"),
        "pipeline_events",
        ["destination_connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_events_pipeline_id"), "pipeline_events", ["pipeline_id"], unique=False
    )
    op.create_table(
        "pipeline_operations",
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("table_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_step", sa.String(length=80), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["table_id"], ["pipeline_tables.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_operations_pipeline_id"),
        "pipeline_operations",
        ["pipeline_id"],
        unique=False,
    )
    op.create_index(
        "ix_pipeline_operations_pipeline_status",
        "pipeline_operations",
        ["pipeline_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_operations_status"), "pipeline_operations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_operations_table_id"), "pipeline_operations", ["table_id"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_operations_type"), "pipeline_operations", ["type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_operations_type"), table_name="pipeline_operations")
    op.drop_index(op.f("ix_pipeline_operations_table_id"), table_name="pipeline_operations")
    op.drop_index(op.f("ix_pipeline_operations_status"), table_name="pipeline_operations")
    op.drop_index("ix_pipeline_operations_pipeline_status", table_name="pipeline_operations")
    op.drop_index(op.f("ix_pipeline_operations_pipeline_id"), table_name="pipeline_operations")
    op.drop_table("pipeline_operations")
    op.drop_index(op.f("ix_pipeline_events_pipeline_id"), table_name="pipeline_events")
    op.drop_index(
        op.f("ix_pipeline_events_destination_connection_id"), table_name="pipeline_events"
    )
    op.drop_index(op.f("ix_pipeline_events_delivery_id"), table_name="pipeline_events")
    op.drop_index(op.f("ix_pipeline_events_connector_id"), table_name="pipeline_events")
    op.drop_table("pipeline_events")
    op.drop_index("ix_notification_delivery_queue", table_name="notification_deliveries")
    op.drop_index(op.f("ix_notification_deliveries_status"), table_name="notification_deliveries")
    op.drop_index(
        op.f("ix_notification_deliveries_channel_id"), table_name="notification_deliveries"
    )
    op.drop_index(op.f("ix_notification_deliveries_alert_id"), table_name="notification_deliveries")
    op.drop_table("notification_deliveries")
    op.drop_table("pipeline_tables")
    op.drop_table("pipeline_metrics")
    op.drop_index(op.f("ix_pipeline_destinations_pipeline_id"), table_name="pipeline_destinations")
    op.drop_index(
        op.f("ix_pipeline_destinations_destination_connection_id"),
        table_name="pipeline_destinations",
    )
    op.drop_index(op.f("ix_pipeline_destinations_actual_state"), table_name="pipeline_destinations")
    op.drop_table("pipeline_destinations")
    op.drop_index(
        "uq_alerts_active_fingerprint",
        table_name="alerts",
        postgresql_where=sa.text("status IN ('firing', 'acknowledged', 'silenced')"),
        sqlite_where=sa.text("status IN ('firing', 'acknowledged', 'silenced')"),
    )
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_source_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_severity"), table_name="alerts")
    op.drop_index("ix_alerts_pipeline_severity", table_name="alerts")
    op.drop_index(op.f("ix_alerts_pipeline_id"), table_name="alerts")
    op.drop_index("ix_alerts_fingerprint_status", table_name="alerts")
    op.drop_index(op.f("ix_alerts_fingerprint"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_event_type"), table_name="alerts")
    op.drop_index("ix_alerts_created_at", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_pipelines_source_connection_id"), table_name="pipelines")
    op.drop_index(op.f("ix_pipelines_actual_state"), table_name="pipelines")
    op.drop_table("pipelines")
    op.drop_table("connectors")
    op.drop_table("source_tables")
    op.drop_index("ix_schema_lookup", table_name="schema_versions")
    op.drop_table("schema_versions")
    op.drop_table("kafka_topics")
    op.drop_index(op.f("ix_connect_clusters_kafka_cluster_id"), table_name="connect_clusters")
    op.drop_table("connect_clusters")
    op.drop_table("alert_rule_channels")
    op.drop_index(op.f("ix_notification_channels_type"), table_name="notification_channels")
    op.drop_index(op.f("ix_notification_channels_enabled"), table_name="notification_channels")
    op.drop_table("notification_channels")
    op.drop_table("kafka_clusters")
    op.drop_index(op.f("ix_connections_status"), table_name="connections")
    op.drop_index(op.f("ix_connections_provider"), table_name="connections")
    op.drop_index(op.f("ix_connections_category"), table_name="connections")
    op.drop_table("connections")
    op.drop_table("secret_references")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_lease_expires_at"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_claimed_by"), table_name="jobs")
    op.drop_index("ix_jobs_claim", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("ix_audit_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("alert_rules")
    # ### end Alembic commands ###
