"""initial_control_plane"""

import sqlalchemy as sa
from alembic import op

revision = "6dc068dd3f4e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_rules",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_created", "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "secret_references",
        sa.Column("ciphertext", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kafka_clusters",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("bootstrap_servers", sa.String(), nullable=False),
        sa.Column("security_protocol", sa.String(), nullable=False),
        sa.Column("secret_ref", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["secret_ref"],
            ["secret_references.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sources",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("environment", sa.String(length=30), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("database_name", sa.String(length=128), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("secret_ref", sa.Uuid(), nullable=False),
        sa.Column("ssl_enabled", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("last_health_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["secret_ref"],
            ["secret_references.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_sources_status"), "sources", ["status"], unique=False)
    op.create_table(
        "connect_clusters",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("kafka_cluster_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["kafka_cluster_id"],
            ["kafka_clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_connect_clusters_kafka_cluster_id"),
        "connect_clusters",
        ["kafka_cluster_id"],
        unique=False,
    )
    op.create_table(
        "kafka_topics",
        sa.Column("kafka_cluster_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["kafka_cluster_id"],
            ["kafka_clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kafka_cluster_id", "name"),
    )
    op.create_table(
        "schema_versions",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("schema_name", sa.String(), nullable=False),
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_json", sa.JSON(), nullable=False),
        sa.Column("schema_hash", sa.String(length=64), nullable=False),
        sa.Column("diff_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "schema_name", "table_name", "version"),
    )
    op.create_index(
        "ix_schema_lookup",
        "schema_versions",
        ["source_id", "schema_name", "table_name"],
        unique=False,
    )
    op.create_table(
        "source_tables",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("schema_name", sa.String(length=128), nullable=False),
        sa.Column("table_name", sa.String(length=128), nullable=False),
        sa.Column("primary_key_columns", sa.JSON(), nullable=False),
        sa.Column("columns_json", sa.JSON(), nullable=False),
        sa.Column("indexes_json", sa.JSON(), nullable=False),
        sa.Column("estimated_rows", sa.BigInteger(), nullable=True),
        sa.Column("estimated_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("cdc_ready", sa.Boolean(), nullable=False),
        sa.Column("cdc_status", sa.String(), nullable=False),
        sa.Column("cdc_issues", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "schema_name", "table_name"),
    )
    op.create_table(
        "connectors",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("connector_type", sa.String(), nullable=False),
        sa.Column("connect_cluster_id", sa.Uuid(), nullable=False),
        sa.Column("connector_class", sa.String(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("desired_state", sa.String(), nullable=False),
        sa.Column("actual_state", sa.String(), nullable=False),
        sa.Column("runtime_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connect_cluster_id"],
            ["connect_clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connect_cluster_id", "name"),
    )
    op.create_table(
        "pipelines",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("kafka_cluster_id", sa.Uuid(), nullable=False),
        sa.Column("connect_cluster_id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=True),
        sa.Column("topic_prefix", sa.String(length=120), nullable=False),
        sa.Column("snapshot_mode", sa.String(), nullable=False),
        sa.Column("config_options", sa.JSON(), nullable=False),
        sa.Column("desired_state", sa.String(), nullable=False),
        sa.Column("actual_state", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connect_cluster_id"],
            ["connect_clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kafka_cluster_id"],
            ["kafka_clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("topic_prefix"),
    )
    op.create_index(op.f("ix_pipelines_actual_state"), "pipelines", ["actual_state"], unique=False)
    op.create_index(op.f("ix_pipelines_source_id"), "pipelines", ["source_id"], unique=False)
    op.create_table(
        "pipeline_events",
        sa.Column("pipeline_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("connector_name", sa.String(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_events_pipeline_id"), "pipeline_events", ["pipeline_id"], unique=False
    )
    op.create_table(
        "pipeline_metrics",
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("values_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline_tables",
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("schema_name", sa.String(), nullable=False),
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("topic_name", sa.String(), nullable=False),
        sa.Column("snapshot_status", sa.String(), nullable=False),
        sa.Column("cdc_status", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pipeline_id", "schema_name", "table_name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pipeline_tables")
    op.drop_table("pipeline_metrics")
    op.drop_index(op.f("ix_pipeline_events_pipeline_id"), table_name="pipeline_events")
    op.drop_table("pipeline_events")
    op.drop_index(op.f("ix_pipelines_source_id"), table_name="pipelines")
    op.drop_index(op.f("ix_pipelines_actual_state"), table_name="pipelines")
    op.drop_table("pipelines")
    op.drop_table("connectors")
    op.drop_table("source_tables")
    op.drop_index("ix_schema_lookup", table_name="schema_versions")
    op.drop_table("schema_versions")
    op.drop_table("kafka_topics")
    op.drop_index(op.f("ix_connect_clusters_kafka_cluster_id"), table_name="connect_clusters")
    op.drop_table("connect_clusters")
    op.drop_index(op.f("ix_sources_status"), table_name="sources")
    op.drop_table("sources")
    op.drop_table("kafka_clusters")
    op.drop_table("secret_references")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("ix_audit_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("alert_rules")
    # ### end Alembic commands ###
