"""destinations"""

import sqlalchemy as sa
from alembic import op

revision = "c25240d70048"
down_revision = "6dc068dd3f4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "destinations",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("environment", sa.String(length=30), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("database_name", sa.String(length=128), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("secret_ref", sa.Uuid(), nullable=False),
        sa.Column("ssl_enabled", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("last_health_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["secret_ref"],
            ["secret_references.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_destinations_status"), "destinations", ["status"], unique=False)
    op.create_table(
        "pipeline_destinations",
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("destination_id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("delivery_mode", sa.String(), nullable=False),
        sa.Column("topic_mapping_json", sa.JSON(), nullable=False),
        sa.Column("configuration_json", sa.JSON(), nullable=False),
        sa.Column("desired_state", sa.String(), nullable=False),
        sa.Column("actual_state", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["destinations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connector_id"),
        sa.UniqueConstraint("destination_id", "name"),
    )
    op.create_index(
        op.f("ix_pipeline_destinations_actual_state"),
        "pipeline_destinations",
        ["actual_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_destinations_destination_id"),
        "pipeline_destinations",
        ["destination_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_destinations_pipeline_id"),
        "pipeline_destinations",
        ["pipeline_id"],
        unique=False,
    )
    op.add_column("pipeline_events", sa.Column("destination_id", sa.Uuid(), nullable=True))
    op.add_column("pipeline_events", sa.Column("connector_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_pipeline_events_connector_id"), "pipeline_events", ["connector_id"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_events_destination_id"),
        "pipeline_events",
        ["destination_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_pipeline_events_destination",
        "pipeline_events",
        "destinations",
        ["destination_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_pipeline_events_connector",
        "pipeline_events",
        "connectors",
        ["connector_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_pipeline_events_connector", "pipeline_events", type_="foreignkey")
    op.drop_constraint("fk_pipeline_events_destination", "pipeline_events", type_="foreignkey")
    op.drop_index(op.f("ix_pipeline_events_destination_id"), table_name="pipeline_events")
    op.drop_index(op.f("ix_pipeline_events_connector_id"), table_name="pipeline_events")
    op.drop_column("pipeline_events", "connector_id")
    op.drop_column("pipeline_events", "destination_id")
    op.drop_index(op.f("ix_pipeline_destinations_pipeline_id"), table_name="pipeline_destinations")
    op.drop_index(
        op.f("ix_pipeline_destinations_destination_id"), table_name="pipeline_destinations"
    )
    op.drop_index(op.f("ix_pipeline_destinations_actual_state"), table_name="pipeline_destinations")
    op.drop_table("pipeline_destinations")
    op.drop_index(op.f("ix_destinations_status"), table_name="destinations")
    op.drop_table("destinations")
    # ### end Alembic commands ###
