apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluecdc
resources:
  - namespace.yaml
  - configmap.yaml
  - metadata.yaml
  - api.yaml
  - web.yaml
  - connect.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: cluecdc
    includeSelectors: true
